### ISSUE TITLE
Failure after following install instructions

### ISSUE THREAD

**Issue by deweycoffman** [RedDrum-Redfish-Project/RedDrum-Simulator#5]
Did a fresh install of Centos 7.4, followed the instructions to install the Simulator and Frontend:

https://github.com/RedDrum-Redfish-Project/RedDrum-Simulator/blob/master/README.md

Backend is NOT installed, but the error below is mentioning the Frontend.

Also, had to install Python 3.6.2, and make symbolic link so python3 could be invoked. Did I miss that as a requirement?

Followed the rest of the install instructions, I "believe" I have everything installed, 

[root@c7laptop RedDrum-Simulator]# ls
AUTHORS.md    README.md              reddrum_simulator           scripts
CHANGELOG.md  RedDrum.conf           RedDrum_Simulator.egg-info  setup.cfg
Docs          RedDrum-Frontend       redDrumSimulatorMain.py     setup.py
LICENSE.txt   RedDrum-Httpd-Configs  requirements.txt
[root@c7laptop RedDrum-Simulator]# cd scripts
[root@c7laptop scripts]# ./runSimulator BaseServer1
Running RedDrum Front-end From Main 
Traceback (most recent call last):
  File "redDrumSimulatorMain", line 234, in <module>
    main(sys.argv)
  File "redDrumSimulatorMain", line 93, in main
    rdVersion=rdVersion, rdProfile=rdProfile)
  File "redDrumSimulatorMain", line 131, in redDrumMain
    from reddrum_frontend import RdRootData   # import the RedDrum Root Data Structure and logMsg Method
ModuleNotFoundError: No module named 'reddrum_frontend'

**Comment by PhillipWatts1012** [comment]
It works for me.


./runRedDrum Simulator BaseServer1


redfishtool -r localhost -u root -p password raw GET /redfish/v1/Systems


________________________________

**Comment by deweycoffman** [comment]
Was this a freshly installed CentOS 7 system? or did you have previous "prerequisites" installed that need to be mentioned?

**Comment by PhillipWatts1012** [comment]
below, and attached is my prep script for new, minimal, centos

set -x
yum -y update
yum -y install less
yum -y install epel-release
yum -y install python-pip
yum -y install git
yum -y install net-tools
yum -y install iproute
yum -y install nmap
yum -y install psmisc
yum  -y install httpd
yum  -y install python34 python-pip

# curl -O https://bootstrap.pypa.io/get-pip.py /usr/bin/python3.4 get-pip.py
# curl didnt work, next 2 instead
yum -y install python34-setuptools
easy_install-3.4 pip

yum  -y groupinstall "Development Tools"
yum  -y install OpenIPMI OpenIPMI-tools
yum  -y install python-devel

pip install -U pip      # update pip
pip3 install virtualenv
pip3 install flask
pip3 install requests
yum -y install redis
pip3 install redis
yum -y install celery
pip3 install celery
## yum doesnt put above tools in site-packages

pip3 install redfishtool
yum -y install mod_ssl openssl
pip3 install passlib==1.7.1
pip3 install pytz         # coming soon requirement

#AND to run dmtf tests
pip3 install jsonschema
pip3 install beautifulsoup4
pip3 install lxml


________________________________

**Comment by manishg4** [comment]
I too am facing a similar issue, and I do not think it is a setup related issue.

Steps:
1. git cloned all of the repos under the redDrum project

2. Ran the FrontEnd project separately (cloned from https://github.com/RedDrum-Redfish-Project/RedDrum-Frontend) as below:
Server :  python3 redDrumMain.py

The above command resulted in the Flask server starting up.

From a client, issued the command "curl -X GET http://127.0.0.1:5001/redfish/v1 -k" and was able to get the schema definition.
Next, tried to access the "Chassis Property" using command: "curl -X GET http://127.0.0.1:5001/redfish/v1/Chassis -k -u redfish_readonly:password_readonly" and was able to see the response JSON object corresponding to the Chassis object,
Since the Members Count is 0 (as it is stubbed), could not progress further to determine chassis property.

3. To navigate through, next tried running the Simulator backend from "https://github.com/RedDrum-Redfish-Project/RedDrum-Simulator", and ran into the issue mentioned in the first comment.

Would ideally like to run the entire simulator and browse through all of the meta data coming from the DB files.

**Comment by manishg4** [comment]
It seems, the issue was due to the "RedDrum-Frontend" path not being set.

The following two lines need to be uncommented in redDrumSimulatorMain.py to set the path to RedDrum-Frontend:


defaultFrontendPath=os.path.abspath(os.path.join(cwd,"RedDrum-Frontend"))
sys.path.append(defaultFrontendPath) # add this to the path

Once the path changes were done as above, I was able to get the simulator up and running using command: python3 redDrumSimulatorMain.py -L --Profile=BaseServer1
